title: Goffaux Lab
subtitle: human vision @UCLouvain
logo-text: false
header: images/background-val.jpg
footer: images/background-val.jpg
links:
  email: goffauxlab@gmail.com
  orcid: 0000-0003-3182-7011
  google-scholar: enBXK1cAAAAJ&hl
  research-gate: lab/GoffauxLab-Valerie-Goffaux
  github: Goffaux-Lab
  linkedin: company/goffauxlab-human-vision-uclouvain/posts/?feedView=all
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      type: members
    values:
      layout: member
  - scope:
      type: posts
    values:
      layout: post
collections:
  members:
    output: true
  posts:
    output: true
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at
highlighter: rouge
theme: null
sass:
  sass_dir: _styles
include:
  - _styles
  - _scripts
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
email: contact@Goffaux-Lab.com
github: Goffaux-Lab
linkedin: company/goffauxlab-human-vision-uclouvain/posts/?feedView=all
instagram: Goffaux-Lab
youtube: Goffaux-Lab
